Repository hyperledger/aries-vcx, pull requests merged in 2020-12, with the labels that each got.

#222 Add prerelease support
  .github/workflows/main.yml
Labels: ci

#219 Split provision into API-exposed stages
  Cargo.lock
  agency_client/src/mocking.rs
  agency_client/src/utils/agent_utils.rs
  libvcx/Cargo.toml
  libvcx/src/api/utils.rs
  libvcx/src/api/wallet.rs
  libvcx/src/aries/mod.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/ledger.rs
  libvcx/src/libindy/utils/mod.rs
  libvcx/src/libindy/utils/signus.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/schema.rs
  libvcx/src/settings.rs
  libvcx/src/utils/author_agreement.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/mod.rs
  libvcx/src/utils/provision.rs
  libvcx/src/utils/random.rs
Labels: enhancement, refactoring

#224 Fix indypool docker image
  .github/workflows/main.yml
  ci/indy-pool.dockerfile
Labels: ci

#208 Remove agency settings
  .github/workflows/main.yml
  Cargo.lock
  agency_client/Cargo.toml
  agency_client/src/agency_client.rs
  agency_client/src/agency_settings.rs
  agency_client/src/agent_utils.rs
  agency_client/src/error.rs
  agency_client/src/get_message.rs
  agency_client/src/httpclient.rs
  agency_client/src/lib.rs
  agency_client/src/message_type.rs
  agency_client/src/mocking.rs
  agency_client/src/update_connection.rs
  agency_client/src/update_message.rs
  agency_client/src/utils/comm.rs
  agency_client/src/utils/create_key.rs
  agency_client/src/utils/encryption_envelope.rs
  agency_client/src/utils/error_utils.rs
  agency_client/src/utils/libindy/crypto.rs
  agency_client/src/utils/libindy/signus.rs
  agency_client/src/utils/mod.rs
  agency_client/src/utils/option_util.rs
  agency_client/src/utils/update_profile.rs
  agency_client/src/utils/validation.rs
  agency_client/src/utils/wallet.rs
  libvcx/src/api/vcx.rs
  libvcx/src/aries/handlers/connection/agent_info.rs
  libvcx/src/aries/handlers/connection/invitee/state_machine.rs
  libvcx/src/connection.rs
  libvcx/src/error/mod.rs
  libvcx/src/init.rs
  libvcx/src/issuer_credential.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/proof.rs
  libvcx/src/settings.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/error.rs
  libvcx/src/utils/provision.rs
Labels: refactoring

#244 Fix incorrect evaluation whether PR is prerelease
  .github/workflows/main.yml
Labels: ci, pre-release

#242 Release/0.15.0
  .github/workflows/main.yml
  Cargo.lock
  agents/node/vcxagent-core/package.json
  libvcx/Cargo.toml
Labels: pre-release
