Repository hyperledger/aries-vcx, pull requests merged in 2020-11, with the labels that each got.

#154 Update rust toolchain to 1.45.2
  .github/workflows/main.yml
  ci/libvcx.dockerfile
  ci/ubuntu.dockerfile
  wrappers/java/ci/android.dockerfile
Labels: ci

#174 Split libvcx alpine image build in 2 phases
  .github/workflows/main.yml
  ci/alpine_core.dockerfile
  ci/libvcx.dockerfile
  libvcx/tails.txt/GedWbCuEYRcXK1ndGUrygAwSw6GDHnEWpoeVuLrZEhan
Labels: ci

#181 Deserialize storage config properly
  libvcx/src/utils/libindy/wallet.rs
Labels: hotfix

#182 Support config on rotation
  agents/node/vcxagent-core/demo/alice.js
  agents/node/vcxagent-core/src/storage/storage-service.js
  agents/node/vcxagent-core/test/distribute-tails.spec.js
  libvcx/src/api/credential_def.rs
  libvcx/src/credential_def.rs
  libvcx/src/lib.rs
Labels: breaking, enhancement

#183 Add ver field to revocation registry definition
  libvcx/src/credential_def.rs
Labels: hotfix

#185 Build arm instead of armv7
  .github/workflows/main.yml
  wrappers/java/ci/setup.android.env.sh
Labels: ci, hotfix

#186 Remove notion of logo_url
  agents/node/vcxagent-core/src/utils/vcx-workflows.js
  libvcx/sample_config/config.json
  libvcx/src/agency_comm/update_profile.rs
  libvcx/src/agency_comm/utils/agent_utils.rs
  libvcx/src/api/vcx.rs
  libvcx/src/settings.rs
  libvcx/src/utils/constants.rs
  libvcx/src/utils/json.rs
  wrappers/node/src/api/init.ts
  wrappers/node/src/api/utils.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/utils.ts
  wrappers/node/test/suite1/ariesvcx-utils.test.ts
  wrappers/python3/vcx/common.py
Labels: refactoring

#184 Remove notion of protocol_type, communication_method
  agents/node/vcxagent-core/src/utils/vcx-workflows.js
  demo/java/src/main/java/Alice.java
  libvcx/sample_config/config.json
  libvcx/src/agency_comm/get_message.rs
  libvcx/src/agency_comm/update_profile.rs
  libvcx/src/agency_comm/utils/agent_utils.rs
  libvcx/src/api/utils.rs
  libvcx/src/api/vcx.rs
  libvcx/src/aries/handlers/connection/agent_info.rs
  libvcx/src/connection.rs
  libvcx/src/settings.rs
  libvcx/src/utils/constants.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/json.rs
  wrappers/node/src/api/connection.ts
  wrappers/node/src/api/credential.ts
  wrappers/node/src/api/disclosed-proof.ts
  wrappers/node/src/api/init.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/api/proof.ts
  wrappers/node/src/api/utils.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/test-constants.ts
  wrappers/node/test/helpers/utils.ts
  wrappers/node/test/suite1/ariesvcx-connection.test.ts
  wrappers/node/test/suite1/ariesvcx-credential-def.test.ts
  wrappers/node/test/suite1/ariesvcx-credential.test.ts
  wrappers/node/test/suite1/ariesvcx-disclosed-proof.test.ts
  wrappers/node/test/suite1/ariesvcx-issuer-credential.test.ts
  wrappers/node/test/suite1/ariesvcx-proof.test.ts
  wrappers/node/test/suite1/ariesvcx-schema.test.ts
  wrappers/node/test/suite1/ariesvcx-utils.test.ts
  wrappers/node/test/suite1/ariesvcx-wallet.test.ts
  wrappers/node/test/suite2/ffi.test.ts
  wrappers/python3/aries-test-server/utils.py
  wrappers/python3/demo/acme.py
  wrappers/python3/demo/alice-pg.py
  wrappers/python3/demo/alice.py
  wrappers/python3/demo/alternate_wallet_path.py
  wrappers/python3/demo/faber-pg.py
  wrappers/python3/demo/faber.py
  wrappers/python3/vcx/common.py
Labels: refactoring

#191 Use revocation details on rev reg rot in node wrapper
  wrappers/node/src/api/credential-def.ts
  wrappers/node/src/rustlib.ts
Labels: hotfix

#195 Add roadmap
  README.md
  roadmap.md
Labels: documentation

#201 Fix iOS wrapper
  libvcx/Cargo.toml
  wrappers/ios/vcx/ConnectMeVcx.h
Labels: hotfix

#199 Delete deprecated init functions, migrate tests
  demo/java/src/main/java/Alice.java
  demo/java/src/main/java/Faber.java
  libvcx/src/api/vcx.rs
  libvcx/src/utils/devsetup.rs
  wrappers/ios/vcx/ConnectMeVcx.h
  wrappers/ios/vcx/ConnectMeVcx.m
  wrappers/ios/vcx/include/libvcx.h
  wrappers/ios/vcx/vcx-demo/AppDelegate.m
  wrappers/ios/vcx/vcx-demoTests/RNIndy.h
  wrappers/ios/vcx/vcx-demoTests/RNIndy.m
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/vcx/VcxApi.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/ConnectionApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/CredentialApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/CredentialDefApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/DisclosedProofApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/ProofApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/SchemaApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/TokenApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/VcxApiTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/VcxUtilsTest.java
  wrappers/java/src/test/java/com/evernym/sdk/vcx/WalletApiTest.java
  wrappers/node/src/api/init.ts
  wrappers/node/src/api/wallet.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/suite1/ariesvcx-wallet.test.ts
  wrappers/node/test/suite2/ffi.test.ts
  wrappers/python3/aries-test-server/utils.py
  wrappers/python3/demo/acme.py
  wrappers/python3/demo/alice-pg.py
  wrappers/python3/demo/alice.py
  wrappers/python3/demo/alternate_wallet_path.py
  wrappers/python3/demo/faber-pg.py
  wrappers/python3/demo/faber.py
  wrappers/python3/tests/conftest.py
  wrappers/python3/tests/test_vcx_init.py
  wrappers/python3/vcx/api/utils.py
  wrappers/python3/vcx/api/vcx_init.py
  wrappers/python3/vcx/api/wallet.py
Labels: breaking, refactoring

#192 Add trustping and feature discovery support to node vcxagent-core
  agents/node/vcxagent-core/package.json
  agents/node/vcxagent-core/src/services/service-connections.js
  agents/node/vcxagent-core/test/feature-discovery.spec.js
  agents/node/vcxagent-core/test/trustping.spec.js
  agents/node/vcxagent-core/test/utils/alice.js
Labels: enhancement

#205 Remove usage of deprecated set-env Github Action feature
  .github/workflows/main.yml
Labels: ci, hotfix

#207 Add and update documentation
  .github/workflows/main.yml
  README.md
  agents/node/vcxagent-cli/readme.md
  agents/node/vcxagent-core/package.json
  agents/node/vcxagent-core/readme.md
Labels: documentation

#212 Release 0.14.0
  Cargo.lock
  libvcx/Cargo.toml
Labels: changelog-excluded

#214 Fix name of android wrapper device artifact
  .github/workflows/main.yml
Labels: ci

#217 Fetch pool image from GitHub Container Registry
  .github/workflows/main.yml
Labels: ci, hotfix

#215 Add CI section config to changelog generator
  .github/workflows/main.yml
Labels: ci

#213 Remove rev reg value caching in build rev states
  Cargo.lock
  libvcx/Cargo.toml
  libvcx/src/libindy/proofs/prover/prover_internal.rs
  libvcx/src/libindy/utils/cache.rs
Labels: bug
