Repository hyperledger/aries-vcx, pull requests merged in 2021-06, with the labels that each got.

#280 Changes related to aries test harness backchannel
  agency_client/src/agent_utils.rs
  agency_client/src/utils/constants.rs
  agency_client/src/utils/libindy/signus.rs
  agents/node/vcxagent-core/test/utils/alice.js
  agents/node/vcxagent-core/test/utils/faber.js
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/connection/invitee/state_machine.rs
  libvcx/src/aries/handlers/connection/invitee/states/complete.rs
  libvcx/src/aries/handlers/connection/invitee/states/mod.rs
  libvcx/src/aries/handlers/connection/invitee/states/requested.rs
  libvcx/src/aries/handlers/connection/invitee/states/responded.rs
  libvcx/src/aries/handlers/connection/inviter/state_machine.rs
  libvcx/src/aries/handlers/connection/inviter/states/complete.rs
  libvcx/src/aries/handlers/connection/inviter/states/invited.rs
  libvcx/src/aries/handlers/connection/inviter/states/mod.rs
  libvcx/src/aries/handlers/connection/inviter/states/requested.rs
  libvcx/src/aries/handlers/connection/messages.rs
  libvcx/src/aries/handlers/connection/mod.rs
  libvcx/src/aries/handlers/issuance/issuer/issuer.rs
  libvcx/src/aries/handlers/issuance/issuer/state_machine.rs
  libvcx/src/aries/mod.rs
  libvcx/src/connection.rs
  libvcx/src/issuer_credential.rs
  libvcx/src/lib.rs
  libvcx/src/libindy/utils/ledger.rs
  libvcx/src/utils/devsetup_agent.rs
  libvcx/src/utils/mod.rs
  wrappers/node/test/suite1/ariesvcx-connection.test.ts
Labels: breaking, enhancement, integration

#288 Connection: Split pairwise and cloud agent information
  .github/actions/codecov-unit-tests/action.yml
  .github/workflows/main.yml
  agency_client/src/lib.rs
  libvcx/Cargo.toml
  libvcx/src/aries/handlers/connection/cloud_agent.rs
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/connection/invitee/state_machine.rs
  libvcx/src/aries/handlers/connection/invitee/states/complete.rs
  libvcx/src/aries/handlers/connection/invitee/states/invited.rs
  libvcx/src/aries/handlers/connection/invitee/states/requested.rs
  libvcx/src/aries/handlers/connection/invitee/states/responded.rs
  libvcx/src/aries/handlers/connection/inviter/state_machine.rs
  libvcx/src/aries/handlers/connection/inviter/states/complete.rs
  libvcx/src/aries/handlers/connection/inviter/states/invited.rs
  libvcx/src/aries/handlers/connection/inviter/states/requested.rs
  libvcx/src/aries/handlers/connection/inviter/states/responded.rs
  libvcx/src/aries/handlers/connection/legacy_agent_info.rs
  libvcx/src/aries/handlers/connection/mod.rs
  libvcx/src/aries/handlers/connection/pairwise_info.rs
  libvcx/src/aries/handlers/connection/util.rs
  libvcx/src/aries/utils/encryption_envelope.rs
  libvcx/src/connection.rs
  libvcx/src/credential_def.rs
  libvcx/src/init.rs
  libvcx/src/libindy/proofs/proof_request.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/schema.rs
  libvcx/src/utils/mockdata/mock_settings.rs
  libvcx/src/utils/mod.rs
  libvcx/src/utils/serialization.rs
Labels: breaking, refactoring

#278 Remove/fees setup
  libvcx/src/api/vcx.rs
  libvcx/src/credential_def.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/payments.rs
  libvcx/src/schema.rs
  libvcx/src/utils/devsetup.rs
Labels: refactoring

#289 Refactor/move tests
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/mod.rs
  libvcx/src/connection.rs
  libvcx/src/lib.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/devsetup_agent.rs
Labels: refactoring

#293 Copy cached cargo into libvcx image to prevent redownloading cargo de…
  .github/workflows/main.yml
  ci/libvcx.dockerfile
Labels: ci

#297 Revert rust version to 1.45.2, release aries-vcx 0.18.3
  .github/workflows/main.yml
  Cargo.lock
  agents/node/vcxagent-core/package.json
  ci/alpine_core.dockerfile
  ci/libvcx.dockerfile
  ci/ubuntu.dockerfile
  libvcx/Cargo.toml
  wrappers/ios/ci/build.sh
  wrappers/java/ci/android.dockerfile
Labels: pre-release

#305 Fix bug in encoding new attributes format
  libvcx/src/aries/handlers/issuance/holder/state_machine.rs
  libvcx/src/aries/handlers/issuance/issuer/utils.rs
  libvcx/src/libindy/utils/anoncreds.rs
Labels: hotfix

#304 Try updating to latest tokio and futures crates
  Cargo.lock
  libvcx/Cargo.toml
Labels: update

#300 Move CloudAgentInfo creation to Connecton constructor
  libvcx/src/aries/handlers/connection/cloud_agent.rs
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/proof_presentation/prover/prover.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/verifier.rs
  libvcx/src/aries/messages/attachment.rs
  libvcx/src/aries/messages/proof_presentation/presentation_request.rs
  libvcx/src/aries/messages/status.rs
  libvcx/src/credential.rs
  libvcx/src/libindy/proofs/proof_request.rs
  libvcx/src/utils/mockdata/mockdata_credex.rs
  libvcx/src/utils/mockdata/mockdata_proof.rs
Labels: refactoring

#306 Use libindy with rusql fix for ios build
  .github/workflows/main.yml
  Cargo.lock
  agency_client/Cargo.toml
  ci/alpine_core.dockerfile
  ci/libvcx.dockerfile
  ci/ubuntu.dockerfile
  libvcx/Cargo.toml
  wrappers/ios/ci/build.sh
  wrappers/java/ci/android.dockerfile
Labels: hotfix, pre-release, update

#299 Make send_message implementation pluggable for Connection FSM
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/connection/invitee/state_machine.rs
  libvcx/src/aries/handlers/connection/invitee/states/complete.rs
  libvcx/src/aries/handlers/connection/inviter/state_machine.rs
  libvcx/src/aries/handlers/connection/inviter/states/complete.rs
  libvcx/src/aries/handlers/connection/inviter/states/responded.rs
  libvcx/src/aries/handlers/connection/util.rs
  libvcx/src/aries/messages/connection/did_doc.rs
  libvcx/src/aries/utils/mod.rs
  libvcx/src/connection.rs
Labels: refactoring

#310 Try to fix occasionally failing integration test.
  libvcx/src/credential_def.rs
Labels: ci, hotfix, tests

#295 Restructure c-files
  aries.md
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_c/credential_def.rs
  libvcx/src/api_lib/api_c/disclosed_proof.rs
  libvcx/src/api_lib/api_c/filters.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/logger.rs
  libvcx/src/api_lib/api_c/mod.rs
  libvcx/src/api_lib/api_c/proof.rs
  libvcx/src/api_lib/api_c/schema.rs
  libvcx/src/api_lib/api_c/utils.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_c/wallet.rs
  libvcx/src/api_lib/api_handle/connection.rs
  libvcx/src/api_lib/api_handle/credential.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  libvcx/src/api_lib/api_handle/disclosed_proof.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/mod.rs
  libvcx/src/api_lib/api_handle/object_cache/mod.rs
  libvcx/src/api_lib/api_handle/proof.rs
  libvcx/src/api_lib/api_handle/schema.rs
  libvcx/src/api_lib/mod.rs
  libvcx/src/api_lib/utils_c/ccallback.rs
  libvcx/src/api_lib/utils_c/cstring.rs
  libvcx/src/api_lib/utils_c/error.rs
  libvcx/src/api_lib/utils_c/fsm_states.rs
  libvcx/src/api_lib/utils_c/mod.rs
  libvcx/src/api_lib/utils_c/return_types_u32.rs
  libvcx/src/api_lib/utils_c/runtime.rs
  libvcx/src/api_lib/utils_c/timeout.rs
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/issuance/holder/state_machine.rs
  libvcx/src/aries/handlers/issuance/issuer/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/prover/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/state_machine.rs
  libvcx/src/aries/mod.rs
  libvcx/src/error/mod.rs
  libvcx/src/init.rs
  libvcx/src/lib.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/devsetup_agent.rs
  libvcx/src/utils/logger.rs
  libvcx/src/utils/mod.rs
  libvcx/src/utils/threadpool.rs
  libvcx/tests/logging.rs
Labels: refactoring
