Repository hyperledger/aries-vcx, pull requests merged in 2021-11, with the labels that each got.

#377 Add code of conduct
  ARIES.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  ROADMAP.md
Labels: documentation

#375 Store thread id on state machine level for connection
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/invitee/state_machine.rs
  aries_vcx/src/handlers/connection/inviter/state_machine.rs
  aries_vcx/src/messages/a2a/mod.rs
  aries_vcx/src/messages/connection/did_doc.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/src/messages/connection/request.rs
  aries_vcx/src/messages/thread.rs
  aries_vcx/src/utils/mockdata/mockdata_connection.rs
  aries_vcx/src/utils/serialization.rs
  aries_vcx/tests/test_integration.rs
  ci/libvcx-codecov.dockerfile
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_handle/connection.rs
Labels: refactoring

#376 Simplify issuer offer sending API
  agents/node/vcxagent-core/src/services/service-cred-issuer.js
  aries_vcx/src/handlers/issuance/issuer/issuer.rs
  aries_vcx/src/handlers/issuance/issuer/state_machine.rs
  aries_vcx/src/handlers/issuance/issuer/states/credential_sent.rs
  aries_vcx/src/handlers/issuance/issuer/states/finished.rs
  aries_vcx/src/handlers/issuance/issuer/states/initial.rs
  aries_vcx/src/handlers/issuance/issuer/states/mod.rs
  aries_vcx/src/handlers/issuance/issuer/states/offer_sent.rs
  aries_vcx/src/handlers/issuance/issuer/states/offer_set.rs
  aries_vcx/src/handlers/issuance/issuer/states/proposal_received.rs
  aries_vcx/src/handlers/issuance/issuer/states/requested_received.rs
  aries_vcx/src/handlers/issuance/messages.rs
  aries_vcx/src/handlers/mod.rs
  aries_vcx/src/lib.rs
  aries_vcx/src/messages/issuance/credential_offer.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_c/credential_def.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/issuer/IssuerApi.java
  wrappers/node/src/api/common.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/entities.ts
  wrappers/node/test/suite1/ariesvcx-issuer-credential.test.ts
Labels: refactoring, breaking

#378 Make thread id optional
  aries_vcx/src/handlers/connection/invitee/state_machine.rs
  aries_vcx/src/handlers/connection/invitee/states/complete.rs
  aries_vcx/src/handlers/connection/invitee/states/invited.rs
  aries_vcx/src/handlers/connection/inviter/state_machine.rs
  aries_vcx/src/handlers/connection/inviter/states/complete.rs
  aries_vcx/src/handlers/connection/inviter/states/responded.rs
  aries_vcx/src/handlers/connection/util.rs
  aries_vcx/src/handlers/issuance/issuer/state_machine.rs
  aries_vcx/src/messages/a2a/mod.rs
  aries_vcx/src/messages/connection/request.rs
  aries_vcx/src/messages/connection/response.rs
  aries_vcx/src/messages/discovery/disclose.rs
  aries_vcx/src/messages/error.rs
  aries_vcx/src/messages/issuance/credential_offer.rs
  aries_vcx/src/messages/issuance/credential_request.rs
  aries_vcx/src/messages/proof_presentation/presentation.rs
  aries_vcx/src/messages/proof_presentation/presentation_proposal.rs
  aries_vcx/src/messages/proof_presentation/presentation_request.rs
  aries_vcx/src/messages/thread.rs
  aries_vcx/src/utils/mockdata/mockdata_connection.rs
  aries_vcx/tests/test_integration.rs
Labels: refactoring

#384 Add config builder methods
  Cargo.lock
  aries_vcx/Cargo.toml
  aries_vcx/src/init.rs
  aries_vcx/src/lib.rs
  aries_vcx/src/libindy/utils/wallet.rs
  aries_vcx/src/utils/provision.rs
Labels: enhancement

#387 Downgrade reqwest
  Cargo.lock
  agency_client/Cargo.toml
  agency_client/src/httpclient.rs
Labels: hotfix

#390 Release 0.24.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded

#391 Release 0.24.1
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package.json
Labels: pre-release

#403 Revert reqwest, futures, tokio upgrade (revision 5502176e6)
  .github/workflows/main.yml
  Cargo.lock
  agency_client/Cargo.toml
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
Labels: pre-release

#404 Release 0.24.2
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package.json
Labels: changelog-excluded

#397 Do not serialize None Filter fields
  aries_vcx/src/libindy/proofs/proof_request.rs
  aries_vcx/src/libindy/proofs/proof_request_internal.rs
Labels: hotfix

#400 Send presentation ack
  aries_vcx/src/handlers/issuance/holder/state_machine.rs
  aries_vcx/src/handlers/proof_presentation/verifier/messages.rs
  aries_vcx/src/handlers/proof_presentation/verifier/state_machine.rs
  aries_vcx/src/handlers/proof_presentation/verifier/verifier.rs
Labels: enhancement
