Repository hyperledger/aries-vcx, pull requests merged in 2021-05, with the labels that each got.

#248 Use RwLock instead of Mutex in ObjectCache
  libvcx/src/utils/object_cache/mod.rs
Labels: enhancement

#256 Prover SM sends Aries messages through a closure
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/proof_presentation/prover/prover.rs
  libvcx/src/aries/handlers/proof_presentation/prover/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/prover/states/presentation_prepared.rs
  libvcx/src/aries/handlers/proof_presentation/prover/states/presentation_prepared_failed.rs
  libvcx/src/connection.rs
  libvcx/src/disclosed_proof.rs
  libvcx/src/libindy/proofs/prover/prover_internal.rs
Labels: refactoring

#272 Verifier SM sends Aries messages through a closure
  libvcx/src/api/proof.rs
  libvcx/src/api/return_types_u32.rs
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/messages.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/states/presentation_request_sent.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/verifier.rs
  libvcx/src/aries/messages/proof_presentation/presentation.rs
  libvcx/src/aries/messages/proof_presentation/presentation_request.rs
  libvcx/src/aries/mod.rs
  libvcx/src/lib.rs
  libvcx/src/libindy/proofs/proof_request.rs
  libvcx/src/proof.rs
Labels: refactoring

#271 Avoid cred def rotation
  libvcx/include/vcx.h
  libvcx/src/api/credential_def.rs
  libvcx/src/aries/messages/proof_presentation/presentation_request.rs
  libvcx/src/credential_def.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/ledger.rs
  wrappers/java/src/main/java/com/evernym/sdk/vcx/credentialDef/CredentialDefApi.java
  wrappers/node/src/api/credential-def.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/entities.ts
  wrappers/node/test/suite1/ariesvcx-credential-def.test.ts
  wrappers/python3/vcx/api/credential_def.py
Labels: enhancement

#203 Use tokio runtime intead of tokio threadpool, update futures crate
  Cargo.lock
  agents/node/vcxagent-core/test/utils/alice.js
  agents/node/vcxagent-core/test/utils/faber.js
  libvcx/Cargo.toml
  libvcx/src/api/connection.rs
  libvcx/src/api/credential.rs
  libvcx/src/api/credential_def.rs
  libvcx/src/api/disclosed_proof.rs
  libvcx/src/api/filters.rs
  libvcx/src/api/issuer_credential.rs
  libvcx/src/api/proof.rs
  libvcx/src/api/schema.rs
  libvcx/src/api/utils.rs
  libvcx/src/api/vcx.rs
  libvcx/src/api/wallet.rs
  libvcx/src/init.rs
  libvcx/src/lib.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/crypto.rs
  libvcx/src/libindy/utils/ledger.rs
  libvcx/src/libindy/utils/mod.rs
  libvcx/src/libindy/utils/payments.rs
  libvcx/src/libindy/utils/pool.rs
  libvcx/src/libindy/utils/signus.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/mod.rs
  libvcx/src/utils/runtime.rs
  libvcx/src/utils/threadpool.rs
Labels: refactoring

#276 Remove/deprecated internal
  libvcx/src/api/utils.rs
  libvcx/src/api/vcx.rs
  libvcx/src/api/wallet.rs
  libvcx/src/aries/handlers/connection/agent_info.rs
  libvcx/src/aries/handlers/connection/mod.rs
  libvcx/src/aries/handlers/issuance/holder/state_machine.rs
  libvcx/src/aries/handlers/issuance/issuer/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/prover/prover.rs
  libvcx/src/aries/handlers/proof_presentation/prover/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/states/presentation_request_sent.rs
  libvcx/src/aries/mod.rs
  libvcx/src/connection.rs
  libvcx/src/init.rs
  libvcx/src/lib.rs
  libvcx/src/libindy/utils/anoncreds.rs
  libvcx/src/libindy/utils/mod.rs
  libvcx/src/libindy/utils/payments.rs
  libvcx/src/libindy/utils/pool.rs
  libvcx/src/libindy/utils/signus.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/schema.rs
  libvcx/src/settings.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/devsetup_agent.rs
  libvcx/src/utils/mod.rs
  libvcx/src/utils/provision.rs
  wrappers/node/test/helpers/utils.ts
  wrappers/node/test/suite1/ariesvcx-wallet.test.ts
Labels: breaking, refactoring
