Repository hyperledger/aries-vcx, pull requests merged in 2021-01, with the labels that each got.

#243 Remove deprecated cred update functions, refactor cred FSM
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/src/services/service-cred-issuer.js
  agents/node/vcxagent-core/src/services/service-prover.js
  agents/node/vcxagent-core/test/update-state-v2.spec.js
  agents/node/vcxagent-core/test/utils/faber.js
  libvcx/src/api/credential.rs
  libvcx/src/api/disclosed_proof.rs
  libvcx/src/api/issuer_credential.rs
  libvcx/src/api/proof.rs
  libvcx/src/aries/handlers/issuance/holder/holder.rs
  libvcx/src/aries/handlers/issuance/holder/state_machine.rs
  libvcx/src/aries/handlers/issuance/holder/states/offer_received.rs
  libvcx/src/aries/handlers/issuance/holder/states/request_sent.rs
  libvcx/src/aries/handlers/issuance/issuer/issuer.rs
  libvcx/src/aries/handlers/issuance/issuer/state_machine.rs
  libvcx/src/aries/handlers/issuance/issuer/states/credential_sent.rs
  libvcx/src/aries/handlers/issuance/issuer/states/initial.rs
  libvcx/src/aries/handlers/issuance/issuer/states/offer_sent.rs
  libvcx/src/aries/handlers/issuance/issuer/states/requested_received.rs
  libvcx/src/aries/handlers/issuance/messages.rs
  libvcx/src/aries/handlers/proof_presentation/prover/messages.rs
  libvcx/src/aries/handlers/proof_presentation/prover/prover.rs
  libvcx/src/aries/handlers/proof_presentation/prover/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/prover/states/finished.rs
  libvcx/src/aries/handlers/proof_presentation/prover/states/presentation_prepared.rs
  libvcx/src/aries/handlers/proof_presentation/prover/states/presentation_prepared_failed.rs
  libvcx/src/aries/handlers/proof_presentation/prover/states/presentation_sent.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/messages.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/state_machine.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/states/finished.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/states/initial.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/states/presentation_request_sent.rs
  libvcx/src/aries/handlers/proof_presentation/verifier/verifier.rs
  libvcx/src/aries/mod.rs
  libvcx/src/credential.rs
  libvcx/src/disclosed_proof.rs
  libvcx/src/issuer_credential.rs
  libvcx/src/lib.rs
  libvcx/src/proof.rs
  wrappers/node/test/suite1/ariesvcx-credential.test.ts
  wrappers/node/test/suite1/ariesvcx-disclosed-proof.test.ts
  wrappers/node/test/suite1/ariesvcx-issuer-credential.test.ts
  wrappers/node/test/suite1/ariesvcx-proof.test.ts
Labels: breaking, wrappers

#251 Send Aries messages against DDO, not against AgentInfo
  libvcx/src/aries/handlers/connection/agent_info.rs
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/connection/invitee/state_machine.rs
  libvcx/src/aries/handlers/connection/invitee/states/complete.rs
  libvcx/src/aries/handlers/connection/invitee/states/requested.rs
  libvcx/src/aries/handlers/connection/inviter/state_machine.rs
  libvcx/src/aries/handlers/connection/inviter/states/complete.rs
  libvcx/src/aries/handlers/connection/inviter/states/invited.rs
  libvcx/src/aries/handlers/connection/util.rs
  libvcx/src/aries/handlers/issuance/holder/holder.rs
  libvcx/src/aries/handlers/proof_presentation/prover/prover.rs
  libvcx/src/aries/handlers/proof_presentation/prover/state_machine.rs
  libvcx/src/aries/messages/connection/did_doc.rs
  libvcx/src/credential.rs
  libvcx/src/disclosed_proof.rs
Labels: refactoring

#255 Refactor/sending messages
  libvcx/src/aries/handlers/connection/agent_info.rs
  libvcx/src/aries/handlers/connection/connection.rs
  libvcx/src/aries/handlers/connection/invitee/state_machine.rs
  libvcx/src/aries/handlers/connection/invitee/states/complete.rs
  libvcx/src/aries/handlers/connection/invitee/states/requested.rs
  libvcx/src/aries/handlers/connection/inviter/state_machine.rs
  libvcx/src/aries/handlers/connection/inviter/states/complete.rs
  libvcx/src/aries/handlers/connection/inviter/states/invited.rs
  libvcx/src/aries/handlers/connection/util.rs
  libvcx/src/aries/handlers/issuance/holder/holder.rs
  libvcx/src/aries/handlers/proof_presentation/prover/prover.rs
  libvcx/src/aries/handlers/proof_presentation/prover/state_machine.rs
  libvcx/src/aries/messages/connection/did_doc.rs
  libvcx/src/aries/messages/proof_presentation/presentation_request.rs
  libvcx/src/connection.rs
  libvcx/src/credential.rs
  libvcx/src/disclosed_proof.rs
Labels: refactoring

#252 Add new init methods to wrappers
  libvcx/src/api/wallet.rs
  wrappers/ios/vcx/ConnectMeVcx.h
  wrappers/ios/vcx/ConnectMeVcx.m
  wrappers/ios/vcx/include/libvcx.h
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/utils/UtilsApi.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/vcx/VcxApi.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/wallet/WalletApi.java
Labels: refactoring

#223 Add new initialization methods
  .github/workflows/main.yml
  agents/node/vcxagent-core/demo/alice.js
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/demo/integration-test.js
  agents/node/vcxagent-core/package.json
  agents/node/vcxagent-core/src/agent.js
  agents/node/vcxagent-core/src/utils/vcx-workflows.js
  libvcx/src/api/utils.rs
  libvcx/src/api/vcx.rs
  libvcx/src/api/wallet.rs
  libvcx/src/init.rs
  libvcx/src/libindy/utils/wallet.rs
  libvcx/src/settings.rs
  libvcx/src/utils/devsetup.rs
  libvcx/src/utils/threadpool.rs
  libvcx/src/utils/version_constants.rs
  wrappers/ios/vcx/ConnectMeVcx.h
  wrappers/ios/vcx/ConnectMeVcx.m
  wrappers/ios/vcx/include/libvcx.h
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/utils/UtilsApi.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/vcx/VcxApi.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/wallet/WalletApi.java
  wrappers/node/src/api/init.ts
  wrappers/node/src/api/utils.ts
  wrappers/node/src/api/wallet.ts
  wrappers/node/src/rustlib.ts
Labels: enhancement
