Repository hyperledger/aries-vcx, pull requests merged in 2021-12, with the labels that each got.

#402 Pass request data to Verifier::create_from_request via struct
  aries_vcx/src/handlers/proof_presentation/verifier/state_machine.rs
  aries_vcx/src/handlers/proof_presentation/verifier/verifier.rs
  aries_vcx/src/libindy/proofs/proof_request.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_handle/proof.rs
Labels: refactoring

#412 Release 0.26.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded

#411 Split create credential definition into two stages
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/src/services/service-ledger-creddef.js
  agents/node/vcxagent-core/test/distribute-tails.spec.js
  agents/node/vcxagent-core/test/utils/faber.js
  aries_vcx/src/handlers/issuance/credential_def/mod.rs
  aries_vcx/src/libindy/utils/anoncreds.rs
  aries_vcx/src/utils/serialization.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_c/credential_def.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/credentialDef/CredentialDefApi.java
  wrappers/node/package-lock.json
  wrappers/node/src/api/credential-def.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/entities.ts
Labels: refactoring, breaking

#405 fix libzmq build error with disable some features
  wrappers/ios/ci/build.sh
  wrappers/ios/ci/patches/libzmq.rb.patch
Labels: ci

#410 Upgrade agency version used in CI
  .github/actions/code-coverage/action.yml
  .github/workflows/main.yml
  ci/agency/docker-compose.yml
  ci/agency/localhost.env
Labels: ci

#386 Update Xcode in iOS CI to version 12.4
  .github/workflows/main.yml
Labels: ci, update

#416 Fix failing download_messages_noauth integration test
  aries_vcx/tests/test_integration.rs
Labels: hotfix

#417 Move `libindy_issuer_create_credential_offer` a layer up
  aries_vcx/src/handlers/issuance/issuer/issuer.rs
  aries_vcx/src/handlers/issuance/issuer/state_machine.rs
  aries_vcx/src/handlers/issuance/messages.rs
Labels: refactoring

#415 Store problem report in initial state
  aries_vcx/src/handlers/connection/invitee/state_machine.rs
  aries_vcx/src/handlers/connection/invitee/states/initial.rs
  aries_vcx/src/handlers/connection/invitee/states/requested.rs
  aries_vcx/src/handlers/connection/invitee/states/responded.rs
  aries_vcx/src/handlers/connection/inviter/state_machine.rs
  aries_vcx/src/handlers/connection/inviter/states/initial.rs
  aries_vcx/src/handlers/connection/inviter/states/invited.rs
  aries_vcx/src/handlers/connection/inviter/states/requested.rs
  aries_vcx/src/handlers/connection/inviter/states/responded.rs
Labels: enhancement

#414 Set correct thread id when responding to public invite
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/invitee/state_machine.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/src/messages/connection/request.rs
Labels: hotfix
