Repository hyperledger/aries-vcx, pull requests merged in 2022-09, with the labels that each got.

#552 Add MAINTAINERS.md file
  MAINTAINERS.md
Labels: documentation

#555 Remove TestAgent trait
  Cargo.lock
  agency_client/src/lib.rs
  aries_vcx/Cargo.toml
  aries_vcx/tests/test_agency.rs
  aries_vcx/tests/test_connection.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/test_pool.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
Labels: refactoring

#556 Eliminate global state: pool handle
  aries_vcx/src/global/mod.rs
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/public_agent.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/out_of_band/receiver.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/src/libindy/credential_def/mod.rs
  aries_vcx/src/libindy/credential_def/revocation_registry.rs
  aries_vcx/src/libindy/proofs/prover/prover.rs
  aries_vcx/src/libindy/proofs/prover/prover_internal.rs
  aries_vcx/src/libindy/proofs/verifier/verifier.rs
  aries_vcx/src/libindy/proofs/verifier/verifier_internal.rs
  aries_vcx/src/libindy/schema/mod.rs
  aries_vcx/src/libindy/utils/anoncreds.rs
  aries_vcx/src/libindy/utils/ledger.rs
  aries_vcx/src/libindy/utils/pool.rs
  aries_vcx/src/libindy/utils/signus.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/src/protocols/connection/invitee/state_machine.rs
  aries_vcx/src/protocols/connection/invitee/states/invited.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/holder/states/offer_received.rs
  aries_vcx/src/protocols/issuance/holder/states/proposal_sent.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/protocols/issuance/mod.rs
  aries_vcx/src/protocols/proof_presentation/prover/state_machine.rs
  aries_vcx/src/protocols/proof_presentation/prover/states/presentation_request_received.rs
  aries_vcx/src/protocols/proof_presentation/verifier/state_machine.rs
  aries_vcx/src/protocols/proof_presentation/verifier/states/presentation_request_sent.rs
  aries_vcx/src/utils/devsetup.rs
  aries_vcx/src/utils/service_resolvable.rs
  aries_vcx/tests/test_agency.rs
  aries_vcx/tests/test_connection.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/test_pool.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/src/api_lib/api_c/schema.rs
  libvcx/src/api_lib/api_c/utils.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_handle/agent.rs
  libvcx/src/api_lib/api_handle/connection.rs
  libvcx/src/api_lib/api_handle/credential.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  libvcx/src/api_lib/api_handle/disclosed_proof.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  libvcx/src/api_lib/api_handle/proof.rs
  libvcx/src/api_lib/api_handle/revocation_registry.rs
  libvcx/src/api_lib/api_handle/schema.rs
  libvcx/src/api_lib/global/mod.rs
  libvcx/src/api_lib/global/pool.rs
  libvcx/src/api_lib/utils/devsetup.rs
Labels: refactoring

#558 Ledger comm/validate response
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/src/services/service-cred-issuer.js
  aries_vcx/src/error.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/libindy/utils/anoncreds.rs
  aries_vcx/src/libindy/utils/cache.rs
  aries_vcx/src/libindy/utils/ledger.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/utils/error.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  wrappers/node/src/api/common.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/rustlib.ts
Labels: breaking

#579 Proof presentation/always ack
  aries_vcx/src/protocols/proof_presentation/prover/state_machine.rs
  aries_vcx/src/protocols/proof_presentation/verifier/state_machine.rs
Labels: hotfix

#580 Remove pool handle from connection protocol
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/out_of_band/receiver.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/src/protocols/connection/invitee/state_machine.rs
  aries_vcx/src/protocols/connection/invitee/states/initial.rs
  aries_vcx/src/protocols/connection/invitee/states/invited.rs
  aries_vcx/src/protocols/connection/invitee/states/requested.rs
  aries_vcx/src/protocols/connection/invitee/states/responded.rs
  aries_vcx/src/utils/mockdata/mockdata_connection.rs
  aries_vcx/tests/test_agency.rs
  aries_vcx/tests/test_connection.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/src/api_lib/api_handle/connection.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
Labels: refactoring

#562 Enhance node agent CLI to support url formatted invitations
  agents/node/vcxagent-cli/package.json
  agents/node/vcxagent-cli/readme.md
  agents/node/vcxagent-cli/vcxclient-cli.js
  agents/node/vcxagent-cli/vcxclient-interactive.js
  agents/node/vcxagent-core/src/agent.js
  agents/node/vcxagent-core/src/utils/vcx-workflows.js
Labels: agents

#586 Make vcx_issuer_send_credential return SM state number
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  wrappers/node/src/api/issuer-credential.ts
Labels: hotfix

#585 Add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: documentation

#588 Builder pattern in agency client configuration
  agency_client/src/agency_client.rs
  aries_vcx/tests/test_agency.rs
  libvcx/src/api_lib/global/agency_client.rs
Labels: hotfix
