Repository hyperledger/aries-vcx, pull requests merged in 2022-11, with the labels that each got.

#634 Replace gradlew repo jcenter() by mavenCentral()
  wrappers/java/android/build.gradle
  wrappers/java/build.gradle
Labels: skip-ios

#637 Fix test-android-build job dependency
  .github/workflows/main.yml
Labels: ci

#635 Revocation status "self-check"
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/indy/anoncreds.rs
  aries_vcx/src/indy/credentials/mod.rs
  aries_vcx/src/indy/primitives/mod.rs
  aries_vcx/src/indy/primitives/revocation_registry_delta.rs
  aries_vcx/src/indy/test_utils.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/utils/scenarios.rs
  rustfmt.toml
Labels: feature

#566 Docs/update
  ARIES.md
  MAINTAINERS.md
  README.md
  ROADMAP.md
  docs/architecture/ariesvcx_architecture_future_150922.png
  docs/architecture/ariesvcx_architecture_now_150922.png
  docs/architecture/ariesvcx_architecture_now_future_150922.drawio
  docs/getting-started.md
  docs/vcx_arch.md
Labels: documentation, skip-ios, skip-android

#641 Expose reading of Aries service from the ledger
  agents/node/vcxagent-core/test/nonmediated-endpoint.spec.js
  agents/node/vcxagent-core/test/utils/faber.js
  aries_vcx/src/indy/ledger/transactions.rs
  libvcx/src/api_lib/api_c/utils.rs
  wrappers/node/src/api/utils.ts
  wrappers/node/src/rustlib.ts
Labels: wrappers

#643 Update node wrapper dependencies
  agents/node/vcxagent-core/package.json
  wrappers/node/package-lock.json
  wrappers/node/package.json
  wrappers/node/src/api/connection.ts
  wrappers/node/src/api/credential-def.ts
  wrappers/node/src/api/credential.ts
  wrappers/node/src/api/disclosed-proof.ts
  wrappers/node/src/api/init.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/api/logging.ts
  wrappers/node/src/api/out-of-band-receiver.ts
  wrappers/node/src/api/out-of-band-sender.ts
  wrappers/node/src/api/proof.ts
  wrappers/node/src/api/public-agent.ts
  wrappers/node/src/api/revocation-registry.ts
  wrappers/node/src/api/schema.ts
  wrappers/node/src/api/utils.ts
  wrappers/node/src/api/vcx-base-with-state.ts
  wrappers/node/src/api/vcx-base.ts
  wrappers/node/src/api/wallet.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/src/utils/ffi-helpers.ts
  wrappers/node/src/vcx.ts
  wrappers/node/test/helpers/utils.ts
  wrappers/node/test/suite1/ariesvcx-connection.test.ts
  wrappers/node/test/suite3/logging.1.test.ts
  wrappers/node/test/suite3/logging.2.test.ts
  wrappers/node/tsconfig.json
Labels: wrappers, update, dependencies

#644 Unify send message closure type
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/indy/signing.rs
  aries_vcx/src/protocols/connection/invitee/state_machine.rs
  aries_vcx/src/protocols/connection/invitee/states/complete.rs
  aries_vcx/src/protocols/connection/invitee/states/requested.rs
  aries_vcx/src/protocols/connection/invitee/states/responded.rs
  aries_vcx/src/protocols/connection/inviter/state_machine.rs
  aries_vcx/src/protocols/mod.rs
Labels: refactoring

#642 create prefix did:sov
  aries_vcx/src/indy/ledger/transactions.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
Labels: feature

#645 Nonmediated connection
  Cargo.lock
  agents/rust/aries-vcx-agent/src/services/connection.rs
  aries_vcx/Cargo.toml
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/mediated_connection.rs
  aries_vcx/src/handlers/connection/mod.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/mod.rs
  aries_vcx/src/handlers/out_of_band/receiver.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/src/handlers/revocation_notification/mod.rs
  aries_vcx/src/lib.rs
  aries_vcx/src/utils/mod.rs
  aries_vcx/tests/test_connection.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/src/api_lib/api_handle/connection.rs
Labels: feature

#649 Add non-mediated connection service to aries-vcx-agent
  agents/rust/aries-vcx-agent/src/agent/agent_config.rs
  agents/rust/aries-vcx-agent/src/agent/agent_struct.rs
  agents/rust/aries-vcx-agent/src/agent/init.rs
  agents/rust/aries-vcx-agent/src/error/convertors.rs
  agents/rust/aries-vcx-agent/src/error/error_kind.rs
  agents/rust/aries-vcx-agent/src/services/connection.rs
  agents/rust/aries-vcx-agent/src/services/holder.rs
  agents/rust/aries-vcx-agent/src/services/issuer.rs
  agents/rust/aries-vcx-agent/src/services/mediated_connection.rs
  agents/rust/aries-vcx-agent/src/services/mod.rs
  agents/rust/aries-vcx-agent/src/services/prover.rs
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  aries_vcx/src/handlers/connection/connection.rs
Labels: feature

#538 Java methods for OOB and LibVcx.api.vcx_get_verkey_from_ledger
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/connection/OutOfBandApi.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/connection/OutOfBandReceiverConnectionExistsResult.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/utils/UtilsApi.java
Labels: wrappers

#646 Run nodejs tests with multiple nodejs versions
  .github/actions/setup-testing-nodejs/action.yml
  .github/workflows/main.yml
  wrappers/node/package.json
Labels: ci, skip-ios, skip-android

#653 Get connection by remote vk, unpack sender vk, remove async, etc.
  agents/rust/aries-vcx-agent/src/agent/mod.rs
  agents/rust/aries-vcx-agent/src/services/connection.rs
  agents/rust/aries-vcx-agent/src/services/holder.rs
  agents/rust/aries-vcx-agent/src/services/issuer.rs
  agents/rust/aries-vcx-agent/src/services/prover.rs
  aries_vcx/src/handlers/connection/cloud_agent.rs
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/mediated_connection.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/protocols/connection/invitee/state_machine.rs
  aries_vcx/src/protocols/proof_presentation/prover/state_machine.rs
  aries_vcx/src/utils/encryption_envelope.rs
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_handle/connection.rs
Labels: refactoring, agents

#655 Appending handshake protocols from node wrapper
  libvcx/src/api_lib/api_handle/out_of_band.rs
  messages/src/a2a/message_type.rs
  messages/src/out_of_band/invitation.rs
  messages/src/out_of_band/mod.rs
  wrappers/node/src/api/out-of-band-sender.ts
  wrappers/node/test/suite1/ariesvcx-oob.test.ts
Labels: wrappers, bugfix

#658 Rename connection -> mediated_connection in api_lib
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_c/disclosed_proof.rs
  libvcx/src/api_lib/api_c/filters.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/mediated_connection.rs
  libvcx/src/api_lib/api_c/mod.rs
  libvcx/src/api_lib/api_c/proof.rs
  libvcx/src/api_lib/api_c/utils.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_handle/credential.rs
  libvcx/src/api_lib/api_handle/disclosed_proof.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/mediated_connection.rs
  libvcx/src/api_lib/api_handle/mod.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  libvcx/src/api_lib/api_handle/proof.rs
  wrappers/node/src/api/credential.ts
  wrappers/node/src/api/disclosed-proof.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/api/mediated-connection.ts
  wrappers/node/src/api/out-of-band-receiver.ts
  wrappers/node/src/api/proof.ts
  wrappers/node/src/api/revocation-registry.ts
  wrappers/node/src/api/utils.ts
  wrappers/node/src/api/vcx-base-with-state.ts
  wrappers/node/src/index.ts
Labels: refactoring

#664 Do not try to publish libvcx image from fork PRs
  .github/actions/construct-run-info/action.yml
  .github/workflows/main.yml
Labels: skip-ios, skip-android

#662 Add other mime type for attributes
  messages/src/issuance/mod.rs
  messages/src/mime_type.rs
Labels: skip-ios, skip-android

#663 iOS Wrapper
  wrappers/ios/ci/build.sh
  wrappers/ios/vcx/ConnectMeVcx.h
  wrappers/ios/vcx/ConnectMeVcx.m
  wrappers/ios/vcx/VcxAPI.h
  wrappers/ios/vcx/VcxAPI.m
  wrappers/ios/vcx/include/libvcx.h
  wrappers/ios/vcx/utils/IndyCallbacks.m
  wrappers/ios/vcx/utils/NSError+VcxError.m
  wrappers/ios/vcx/utils/VcxLogger.h
  wrappers/ios/vcx/utils/VcxLogger.m
  wrappers/ios/vcx/utils/VcxTypes.h
  wrappers/ios/vcx/utils/VcxWrapperCallbacks.h
  wrappers/ios/vcx/utils/VcxWrapperCallbacks.m
  wrappers/ios/vcx/vcx-demo/AppDelegate.m
  wrappers/ios/vcx/vcx-demoTests/RNIndy.m
  wrappers/ios/vcx/vcx.xcodeproj/project.pbxproj
  wrappers/ios/vcx/vcx/vcx.h
Labels: skip-android

#671 Implement Storage trait for agent's ObjectCache
  agents/rust/aries-vcx-agent/src/services/connection.rs
  agents/rust/aries-vcx-agent/src/services/credential_definition.rs
  agents/rust/aries-vcx-agent/src/services/holder.rs
  agents/rust/aries-vcx-agent/src/services/issuer.rs
  agents/rust/aries-vcx-agent/src/services/mediated_connection.rs
  agents/rust/aries-vcx-agent/src/services/prover.rs
  agents/rust/aries-vcx-agent/src/services/revocation_registry.rs
  agents/rust/aries-vcx-agent/src/services/schema.rs
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  agents/rust/aries-vcx-agent/src/storage/mod.rs
  agents/rust/aries-vcx-agent/src/storage/object_cache.rs
Labels: agents
