Repository hyperledger/aries-vcx, pull requests merged in 2022-05, with the labels that each got.

#485 Append txn author agreement to verkey rotatation request
  aries_vcx/src/libindy/utils/signus.rs
Labels: hotfix

#484 Add get txn feature
  aries_vcx/src/libindy/utils/anoncreds.rs
  aries_vcx/src/libindy/utils/ledger.rs
  libvcx/src/api_lib/api_c/utils.rs
  wrappers/node/src/api/utils.ts
  wrappers/node/src/rustlib.ts
Labels: enhancement

#486 Prune container dependencies
  .github/workflows/main.yml
  ci/libvcx-tester.dockerfile
  ci/libvcx.dockerfile
Labels: refactoring

#490 Fix codecov build
  ci/libvcx-codecov.dockerfile
Labels: ci
