Repository hyperledger/aries-vcx, pull requests merged in 2022-02, with the labels that each got.

#438 Out of Band 1.1 handshake reuse protocol
  agents/node/vcxagent-core/src/services/service-out-of-band.js
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/public_agent.rs
  aries_vcx/src/handlers/out_of_band/mod.rs
  aries_vcx/src/handlers/out_of_band/receiver.rs
  aries_vcx/src/handlers/out_of_band/sender.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/messages/a2a/mod.rs
  aries_vcx/src/messages/connection/did_doc.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/src/messages/connection/request.rs
  aries_vcx/src/messages/mod.rs
  aries_vcx/src/messages/out_of_band/handshake_reuse.rs
  aries_vcx/src/messages/out_of_band/handshake_reuse_accepted.rs
  aries_vcx/src/messages/out_of_band/mod.rs
  aries_vcx/src/messages/thread.rs
  aries_vcx/src/protocols/connection/invitee/state_machine.rs
  aries_vcx/src/protocols/connection/invitee/states/complete.rs
  aries_vcx/src/protocols/connection/inviter/state_machine.rs
  aries_vcx/src/protocols/connection/inviter/states/complete.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_c/agent.rs
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_c/out_of_band.rs
  libvcx/src/api_lib/api_handle/agent.rs
  libvcx/src/api_lib/api_handle/connection.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  wrappers/node/package-lock.json
  wrappers/node/src/api/connection.ts
  wrappers/node/src/api/out-of-band-receiver.ts
  wrappers/node/src/api/out-of-band-sender.ts
  wrappers/node/src/api/public-agent.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/suite1/ariesvcx-oob.test.ts
Labels: enhancement

#440 Release 0.30.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded, pre-release

#441 Copy on write access
  aries_vcx/src/handlers/connection/public_agent.rs
  aries_vcx/src/handlers/out_of_band/receiver.rs
  libvcx/src/api_lib/api_c/agent.rs
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_c/disclosed_proof.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/out_of_band.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_handle/agent.rs
  libvcx/src/api_lib/api_handle/connection.rs
  libvcx/src/api_lib/api_handle/credential.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  libvcx/src/api_lib/api_handle/disclosed_proof.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/mod.rs
  libvcx/src/api_lib/api_handle/object_cache/mod.rs
  libvcx/src/api_lib/api_handle/object_cache_async/mod.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  libvcx/src/api_lib/api_handle/proof.rs
  libvcx/src/api_lib/api_handle/schema.rs
Labels: enhancement

#442 Release 0.31.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package.json
Labels: pre-release

#443 Fix vcx_out_of_band_receiver_connection_exists, add test
  agents/node/vcxagent-core/src/services/service-out-of-band.js
  agents/node/vcxagent-core/test/out-of-band.spec.js
  agents/node/vcxagent-core/test/utils/alice.js
  wrappers/node/src/api/out-of-band-receiver.ts
Labels: bug, hotfix

#447 Allow revoking from other than final states
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
Labels: enhancement

#445 Add send connection reuse handshake to wrappers
  wrappers/ios/vcx/ConnectMeVcx.h
  wrappers/ios/vcx/ConnectMeVcx.m
  wrappers/ios/vcx/include/libvcx.h
  wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
  wrappers/java/src/main/java/com/evernym/sdk/vcx/connection/ConnectionApi.java
Labels: wrappers

#446 Release 0.32.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded

#448 Wait for ack
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/src/services/service-cred-issuer.js
  agents/node/vcxagent-core/test/update-state-v2.spec.js
  agents/node/vcxagent-core/test/utils/faber.js
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/protocols/issuance/issuer/states/requested_received.rs
  aries_vcx/tests/utils/devsetup_agent.rs
Labels: enhancement

#452 Change issuer's implementation of is_revokable
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/protocols/issuance/issuer/states/proposal_received.rs
  aries_vcx/tests/test_integration.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/rustlib.ts
Labels: breaking
