Repository hyperledger/aries-vcx, pull requests merged in 2022-01, with the labels that each got.

#420 Decouple generating and sending credential offer
  agents/node/vcxagent-core/src/services/service-agents.js
  agents/node/vcxagent-core/src/services/service-cred-issuer.js
  agents/node/vcxagent-core/src/services/service-out-of-band.js
  agents/node/vcxagent-core/src/services/service-verifier.js
  agents/node/vcxagent-core/test/distribute-tails.spec.js
  agents/node/vcxagent-core/test/out-of-band.spec.js
  agents/node/vcxagent-core/test/update-state-v2.spec.js
  agents/node/vcxagent-core/test/utils/alice.js
  agents/node/vcxagent-core/test/utils/faber.js
  agents/node/vcxagent-core/test/utils/utils.js
  aries_vcx/src/handlers/issuance/issuer/issuer.rs
  aries_vcx/src/handlers/issuance/issuer/state_machine.rs
  aries_vcx/src/handlers/issuance/issuer/states/mod.rs
  aries_vcx/src/handlers/issuance/issuer/states/offer_set.rs
  aries_vcx/src/handlers/issuance/messages.rs
  aries_vcx/src/handlers/mod.rs
  aries_vcx/src/handlers/out_of_band/sender/sender.rs
  aries_vcx/src/handlers/proof_presentation/verifier/messages.rs
  aries_vcx/src/handlers/proof_presentation/verifier/state_machine.rs
  aries_vcx/src/handlers/proof_presentation/verifier/states/presentation_proposal_received.rs
  aries_vcx/src/handlers/proof_presentation/verifier/states/presentation_request_set.rs
  aries_vcx/src/handlers/proof_presentation/verifier/verifier.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/src/messages/issuance/credential_offer.rs
  aries_vcx/src/messages/issuance/credential_proposal.rs
  aries_vcx/src/messages/issuance/mod.rs
  aries_vcx/src/messages/proof_presentation/presentation.rs
  aries_vcx/src/messages/proof_presentation/presentation_proposal.rs
  aries_vcx/src/messages/proof_presentation/presentation_request.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/out_of_band.rs
  libvcx/src/api_lib/api_c/proof.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  libvcx/src/api_lib/api_handle/proof.rs
  wrappers/node/package-lock.json
  wrappers/node/src/api/common.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/api/proof.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/suite1/ariesvcx-issuer-credential.test.ts
  wrappers/node/test/suite1/ariesvcx-proof.test.ts
Labels: enhancement

#427 Change/public invitations api
  agents/node/vcxagent-core/src/agent.js
  agents/node/vcxagent-core/src/services/service-public-agents.js
  agents/node/vcxagent-core/src/storage/storage-service.js
  agents/node/vcxagent-core/test/utils/faber.js
  aries_vcx/src/handlers/connection/public_agent.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_c/agent.rs
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_handle/agent.rs
  libvcx/src/api_lib/api_handle/connection.rs
  wrappers/node/src/api/connection.ts
  wrappers/node/src/api/public-agent.ts
  wrappers/node/src/index.ts
  wrappers/node/src/rustlib.ts
Labels: breaking

#425 Release 0.28.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: pre-release

#428 Add support for OOB messages with DID as service value
  agents/node/vcxagent-core/src/services/service-out-of-band.js
  agents/node/vcxagent-core/test/out-of-band.spec.js
  agents/node/vcxagent-core/test/utils/faber.js
  agents/node/vcxagent-core/test/utils/utils.js
  aries_vcx/src/handlers/out_of_band/sender/sender.rs
  libvcx/src/api_lib/api_c/out_of_band.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  wrappers/node/package.json
  wrappers/node/src/api/out-of-band-sender.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/suite1/ariesvcx-oob.test.ts
Labels: enhancement, bugfix

#431 Release 0.29.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package.json
Labels: changelog-excluded

#432 Update tokio and libc
  Cargo.lock
  agency_client/Cargo.toml
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
Labels: update

#413 Fallback thread id comparison to pthid
  aries_vcx/src/messages/thread.rs
Labels: hotfix

#429 Refactor credential definition code, separate rotation and publishing…
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/src/common.js
  agents/node/vcxagent-core/test/distribute-tails.spec.js
  aries_vcx/src/handlers/issuance/credential_def/mod.rs
  aries_vcx/src/handlers/issuance/credential_def/revocation_registry.rs
  aries_vcx/src/handlers/proof_presentation/prover/prover.rs
  aries_vcx/src/libindy/proofs/prover/prover_internal.rs
  aries_vcx/src/libindy/utils/anoncreds.rs
  aries_vcx/src/utils/constants.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_c/credential_def.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  wrappers/node/src/api/credential-def.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/entities.ts
Labels: refactoring, breaking

#434 Remove unused rev_reg_ids cache
  aries_vcx/src/libindy/utils/cache.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
Labels: refactoring

#435 Validate DIDs on Did struct creation
  aries_vcx/src/handlers/connection/public_agent.rs
  aries_vcx/src/handlers/out_of_band/sender/sender.rs
  aries_vcx/src/libindy/utils/ledger.rs
  aries_vcx/src/messages/connection/did.rs
  aries_vcx/src/messages/connection/did_doc.rs
  aries_vcx/src/messages/connection/invite.rs
  aries_vcx/src/messages/connection/mod.rs
  aries_vcx/src/messages/connection/service.rs
  aries_vcx/src/utils/constants.rs
  aries_vcx/tests/test_integration.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  libvcx/src/api_lib/api_handle/connection.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
Labels: enhancement
