Repository hyperledger/aries-vcx, pull requests merged in 2022-04, with the labels that each got.

#465 JSON-formatted logging
  Cargo.lock
  agency_client/Cargo.toml
  agents/rust/.DS_Store
  aries_vcx/Cargo.toml
  aries_vcx/src/utils/test_logger.rs
  libvcx/Cargo.toml
  libvcx/src/api_lib/utils/logger.rs
Labels: enhancement

#467 Prevent double serialization of service attrib
  aries_vcx/src/libindy/utils/ledger.rs
Labels: bugfix

#466 Update vcxagency
  .github/workflows/main.yml
  agency_client/src/update_message.rs
  agency_client/src/utils/test_constants.rs
  ci/agency/docker-compose.yml
  ci/agency/localhost.env
  ci/alpine_core.dockerfile
  ci/libvcx.dockerfile
  wrappers/ios/ci/build.sh
  wrappers/java/ci/android.dockerfile
Labels: update

#480 Fix ci: caching, mysql test build, nodejs
  .github/workflows/main.yml
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/test/utils/faber.js
  aries_vcx/tests/test_mysql_wallet.rs
Labels: ci

#477 Npm/upgrade
  ci/libvcx-tester.dockerfile
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: ci

#478 Expose verkey rotation
  agency_client/src/mocking.rs
  aries_vcx/src/init.rs
  aries_vcx/src/libindy/utils/ledger.rs
  aries_vcx/src/libindy/utils/mocks/did_mocks.rs
  aries_vcx/src/libindy/utils/mocks/mod.rs
  aries_vcx/src/libindy/utils/mocks/pool_mocks.rs
  aries_vcx/src/libindy/utils/mod.rs
  aries_vcx/src/libindy/utils/signus.rs
  aries_vcx/src/libindy/utils/wallet.rs
  aries_vcx/src/utils/devsetup.rs
  aries_vcx/src/utils/mockdata/mockdata_pool.rs
  aries_vcx/src/utils/mockdata/mod.rs
  libvcx/src/api_lib/api_c/utils.rs
  wrappers/node/src/api/utils.ts
  wrappers/node/src/rustlib.ts
  wrappers/node/test/helpers/utils.ts
Labels: enhancement
