Repository hyperledger/aries-vcx, pull requests merged in 2022-12, with the labels that each got.

#686 Fix legacy wrapper ios release
  .github/workflows/main.yml
Labels: pre-release

#676 Handle did:sov service omitting routing_keys attribute
  aries_vcx/src/indy/ledger/transactions.rs
  aries_vcx/tests/test_pool.rs
Labels: bugfix

#687 Release 0.49.1
  Cargo.lock
  Cargo.toml
  agents/node/vcxagent-core/package.json
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: pre-release

#684 Replace failure crate with thiserror
  Cargo.lock
  agency_client/Cargo.toml
  agency_client/src/error.rs
  agents/rust/aries-vcx-agent/Cargo.toml
  agents/rust/aries-vcx-agent/src/error/error_kind.rs
  aries_vcx/Cargo.toml
  aries_vcx/src/common/ledger/transactions.rs
  aries_vcx/src/error.rs
  aries_vcx/src/indy/ledger/transactions.rs
  aries_vcx/src/indy/signing.rs
  aries_vcx/src/utils/serialization.rs
  libvcx/Cargo.toml
  libvcx/src/api_lib/utils/error.rs
  messages/Cargo.toml
  messages/src/error.rs
Labels: refactoring, agents, dependencies

#668 revealed parameter in prover building proof
  aries_vcx/src/common/proofs/prover/prover_internal.rs
Labels: feature

#693 Unify Rust edition
  Cargo.toml
  agents/rust/aries-vcx-agent/Cargo.toml
  messages/Cargo.toml
Labels: update

#691 689 support didkey aries rfc 0360
  aries_vcx/Cargo.toml
  aries_vcx/src/common/ledger/transactions.rs
  messages/src/did_doc/mod.rs
  messages/src/out_of_band/invitation.rs
Labels: feature
