Repository hyperledger/aries-vcx, pull requests merged in 2022-03, with the labels that each got.

#453 Expose decline offer in node API
  agents/node/vcxagent-core/src/services/service-cred-holder.js
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/tests/test_integration.rs
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_handle/credential.rs
  wrappers/node/src/api/credential.ts
  wrappers/node/src/rustlib.ts
Labels: wrappers

#454 Expose update state with message in node wrapper
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/src/api/proof.ts
  wrappers/node/src/rustlib.ts
Labels: wrappers

#455 Release 0.33.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded, pre-release

#456 Unify err handling code in libvcx, use error level instead of warn
  libvcx/src/api_lib/api_c/agent.rs
  libvcx/src/api_lib/api_c/connection.rs
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_c/credential_def.rs
  libvcx/src/api_lib/api_c/disclosed_proof.rs
  libvcx/src/api_lib/api_c/filters.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/out_of_band.rs
  libvcx/src/api_lib/api_c/proof.rs
  libvcx/src/api_lib/api_c/schema.rs
  libvcx/src/api_lib/api_c/utils.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_c/wallet.rs
Labels: refactoring

#457 Optimize httpclient
  Cargo.lock
  agency_client/Cargo.toml
  agency_client/src/httpclient.rs
  agency_client/src/lib.rs
Labels: bugfix

#458 Download no auth messages by id
  aries_vcx/src/handlers/connection/cloud_agent.rs
  aries_vcx/src/handlers/connection/connection.rs
  aries_vcx/src/handlers/connection/public_agent.rs
Labels: hotfix

#459 Improve http client error handling
  .github/workflows/main.yml
  agency_client/src/httpclient.rs
  agency_client/src/utils/comm.rs
  aries_vcx/src/error.rs
Labels: refactoring

#461 Release 0.34.0
  Cargo.lock
  agents/node/vcxagent-core/package.json
  aries_vcx/Cargo.toml
  libvcx/Cargo.toml
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded
