Repository hyperledger/aries-vcx, pull requests merged in 2022-10, with the labels that each got.

#589 Avoid adding extra quotes when building offer from proposal in array format
  aries_vcx/src/handlers/issuance/issuer.rs
Labels: hotfix

#591 Agency client configure() takes wallet handle as argument
  agency_client/src/agency_client.rs
  aries_vcx/tests/test_agency.rs
  libvcx/src/api_lib/global/agency_client.rs
Labels: refactoring

#575 Simplify build of libvcx.so
  .github/actions/code-coverage/action.yml
  .github/workflows/main.yml
  Cargo.lock
  agency_client/Cargo.toml
  aries_vcx/Cargo.toml
  ci/alpine_core.dockerfile
  ci/libvcx-codecov.dockerfile
  ci/libvcx-tester.dockerfile
  ci/libvcx.dockerfile
  docs/build-general.md
  libvcx/Cargo.toml
  libvcx/build.rs
  libvcx/src/api_lib/utils/logger.rs
  messages/Cargo.toml
  wrappers/ios/ci/build.sh
  wrappers/java/ci/android.build.sh
  wrappers/java/ci/android.dockerfile
  wrappers/java/ci/android.test.sh
  wrappers/java/ci/android.wrapper.test.sh
  wrappers/java/ci/setup.android.env.sh
Labels: ci, dependencies

#598 Always use tokio runtime
  Cargo.lock
  libvcx/Cargo.toml
  libvcx/src/api_lib/utils/runtime.rs
Labels: breaking

#595 Remove unused imports
  Cargo.lock
  agency_client/Cargo.toml
  agency_client/src/lib.rs
  agency_client/src/messages/create_key.rs
  agency_client/src/messages/update_com_method.rs
  agency_client/src/testing/test_utils.rs
  agency_client/src/utils/validation.rs
  aries_vcx/Cargo.toml
  aries_vcx/src/global/settings.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/indy/anoncreds.rs
  aries_vcx/src/indy/credentials/encoding.rs
  aries_vcx/src/indy/credentials/holder/mod.rs
  aries_vcx/src/indy/primitives/credential_definition.rs
  aries_vcx/src/indy/primitives/credential_schema.rs
  aries_vcx/src/indy/primitives/mod.rs
  aries_vcx/src/indy/proofs/prover/mod.rs
  aries_vcx/src/indy/proofs/prover/prover.rs
  aries_vcx/src/indy/proofs/prover/prover_internal.rs
  aries_vcx/src/indy/proofs/verifier/verifier.rs
  aries_vcx/src/indy/proofs/verifier/verifier_internal.rs
  aries_vcx/src/indy/proofs/verifier/verifier_libindy.rs
  aries_vcx/src/indy/test_utils.rs
  aries_vcx/src/indy/wallet.rs
  aries_vcx/src/lib.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/utils/devsetup.rs
  aries_vcx/src/utils/test_logger.rs
  aries_vcx/src/utils/validation.rs
  aries_vcx/tests/test_agency.rs
  aries_vcx/tests/test_connection.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/test_mysql_wallet.rs
  aries_vcx/tests/test_pool.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/Cargo.toml
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_c/credential_def.rs
  libvcx/src/api_lib/api_c/issuer_credential.rs
  libvcx/src/api_lib/api_c/schema.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_c/wallet.rs
  libvcx/src/api_lib/api_handle/credential.rs
  libvcx/src/api_lib/api_handle/credential_def.rs
  libvcx/src/api_lib/api_handle/issuer_credential.rs
  libvcx/src/api_lib/api_handle/out_of_band.rs
  libvcx/src/api_lib/api_handle/revocation_registry.rs
  libvcx/src/api_lib/api_handle/schema.rs
  libvcx/src/api_lib/global/wallet.rs
  libvcx/src/api_lib/utils/logger.rs
  libvcx/src/lib.rs
  messages/Cargo.toml
  messages/src/lib.rs
  messages/src/utils/test_logger.rs
Labels: refactoring

#604 Rust aries agent
  Cargo.lock
  Cargo.toml
  agents/rust/aries-vcx-agent/.gitignore
  agents/rust/aries-vcx-agent/Cargo.toml
  agents/rust/aries-vcx-agent/src/agent/agent_config.rs
  agents/rust/aries-vcx-agent/src/agent/agent_struct.rs
  agents/rust/aries-vcx-agent/src/agent/init.rs
  agents/rust/aries-vcx-agent/src/agent/mod.rs
  agents/rust/aries-vcx-agent/src/error/convertors.rs
  agents/rust/aries-vcx-agent/src/error/error_kind.rs
  agents/rust/aries-vcx-agent/src/error/error_struct.rs
  agents/rust/aries-vcx-agent/src/error/mod.rs
  agents/rust/aries-vcx-agent/src/error/result.rs
  agents/rust/aries-vcx-agent/src/lib.rs
  agents/rust/aries-vcx-agent/src/services/connection.rs
  agents/rust/aries-vcx-agent/src/services/credential_definition.rs
  agents/rust/aries-vcx-agent/src/services/holder.rs
  agents/rust/aries-vcx-agent/src/services/issuer.rs
  agents/rust/aries-vcx-agent/src/services/mod.rs
  agents/rust/aries-vcx-agent/src/services/prover.rs
  agents/rust/aries-vcx-agent/src/services/revocation_registry.rs
  agents/rust/aries-vcx-agent/src/services/schema.rs
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  agents/rust/aries-vcx-agent/src/storage/mod.rs
  agents/rust/aries-vcx-agent/src/storage/object_cache.rs
Labels: feature

#607 Fix agent build
  agents/rust/aries-vcx-agent/src/services/holder.rs
Labels: hotfix

#603 Refactor CI using composite actions
  .github/actions/build-image/action.yml
  .github/actions/code-coverage/action.yml
  .github/actions/construct-run-info/action.yml
  .github/actions/derive-cache-info/action.yml
  .github/actions/load-image/action.yml
  .github/actions/publish-android/action.yml
  .github/actions/publish-image/action.yml
  .github/actions/setup-testing/action.yml
  .github/actions/upload-docker-logs/action.yml
  .github/workflows/main.yml
  aries_vcx/Cargo.toml
  aries_vcx/tests/test_agency.rs
  ci/agency/docker-compose.yml
  ci/libvcx-codecov.dockerfile
  ci/libvcx-tester.dockerfile
  ci/libvcx.dockerfile
  ci/util.sh
  libvcx/Cargo.toml
  libvcx/readme.md
  libvcx/src/api_lib/api_c/credential.rs
  libvcx/src/api_lib/api_c/vcx.rs
  libvcx/src/api_lib/api_handle/credential.rs
Labels: ci

#612 Use a macro for message fetching functions in agent
  agents/rust/aries-vcx-agent/src/services/connection.rs
Labels: refactoring

#602 Update Rust toolchain to 1.64.0
  .github/actions/code-coverage/action.yml
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  agency_client/Cargo.toml
  aries_vcx/Cargo.toml
  ci/alpine_core.dockerfile
  ci/libvcx-codecov.dockerfile
  ci/libvcx-tester.dockerfile
  libvcx/Cargo.toml
  messages/Cargo.toml
  wrappers/ios/ci/build.sh
  wrappers/java/ci/android.dockerfile
Labels: update

#614 Allow obtaining cred rev id from the wallet
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/indy/credentials/holder/mod.rs
  aries_vcx/src/indy/credentials/mod.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/holder/states/finished.rs
Labels: feature

#613 Ci/improvements
  .github/actions/build-image/action.yml
  .github/actions/construct-run-info/action.yml
  .github/actions/derive-cache-info/action.yml
  .github/actions/detect-skip-info/action.yml
  .github/workflows/main.yml
Labels: skip-ios, skip-android

#610 Refactor issuer / holder SMs
  agents/rust/aries-vcx-agent/src/services/holder.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/indy/primitives/credential_definition.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/utils/test_logger.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/src/api_lib/api_handle/credential.rs
Labels: refactoring, skip-ios, skip-android

#626 Publish branch image builds in publishing jobs
  .github/actions/has-image/action.yml
  .github/actions/publish-image/action.yml
Labels: skip-ios, skip-android

#611 Refactor verifier / prover SMs
  agents/rust/aries-vcx-agent/src/services/prover.rs
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/src/protocols/proof_presentation/prover/state_machine.rs
  aries_vcx/src/protocols/proof_presentation/verifier/state_machine.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx/src/api_lib/api_handle/disclosed_proof.rs
Labels: refactoring, skip-ios, skip-android

#621 Use Status enums instead of u32
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/src/protocols/proof_presentation/verifier/state_machine.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  aries_vcx/tests/utils/test_macros.rs
  libvcx/src/api_lib/api_handle/proof.rs
Labels: refactoring, hacktoberfest, skip-ios, skip-android

#608 Revocation notification
  aries_vcx/src/error.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/mod.rs
  aries_vcx/src/handlers/revocation_notification/mod.rs
  aries_vcx/src/handlers/revocation_notification/receiver.rs
  aries_vcx/src/handlers/revocation_notification/sender.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/protocols/mod.rs
  aries_vcx/src/protocols/revocation_notification/mod.rs
  aries_vcx/src/protocols/revocation_notification/receiver/mod.rs
  aries_vcx/src/protocols/revocation_notification/receiver/state_machine.rs
  aries_vcx/src/protocols/revocation_notification/receiver/states/finished.rs
  aries_vcx/src/protocols/revocation_notification/receiver/states/initial.rs
  aries_vcx/src/protocols/revocation_notification/receiver/states/mod.rs
  aries_vcx/src/protocols/revocation_notification/receiver/states/received.rs
  aries_vcx/src/protocols/revocation_notification/sender/mod.rs
  aries_vcx/src/protocols/revocation_notification/sender/state_machine.rs
  aries_vcx/src/protocols/revocation_notification/sender/states/finished.rs
  aries_vcx/src/protocols/revocation_notification/sender/states/initial.rs
  aries_vcx/src/protocols/revocation_notification/sender/states/mod.rs
  aries_vcx/src/protocols/revocation_notification/sender/states/sent.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  messages/src/a2a/message_family.rs
  messages/src/a2a/mod.rs
  messages/src/a2a/protocol_registry.rs
  messages/src/ack/mod.rs
  messages/src/ack/please_ack.rs
  messages/src/connection/response.rs
  messages/src/issuance/credential.rs
  messages/src/lib.rs
  messages/src/proof_presentation/presentation.rs
  messages/src/revocation_notification/mod.rs
  messages/src/revocation_notification/revocation_ack.rs
  messages/src/revocation_notification/revocation_notification.rs
Labels: feature, skip-ios, skip-android

#622 Run tests directly on GA runner
  .github/actions/code-coverage/action.yml
  .github/actions/setup-codecov-rust/action.yml
  .github/actions/setup-testing-nodejs/action.yml
  .github/actions/setup-testing-rust/action.yml
  .github/actions/setup-testing/action.yml
  .github/workflows/main.yml
  ci/indy-pool.dockerfile
  ci/libvcx-codecov.dockerfile
  ci/libvcx-tester.dockerfile
Labels: skip-ios

#630 Release 0.45.0
  Cargo.lock
  Cargo.toml
  agents/node/vcxagent-core/package.json
  wrappers/node/package-lock.json
  wrappers/node/package.json
Labels: changelog-excluded
