Repository hyperledger/aries-vcx, pull requests merged in 2023-07, with the labels that each got.

#890 Enable compiling the workspace with --tests --all-features
  .github/workflows/main.yml
  Cargo.lock
  libvcx/src/lib.rs
  libvcx_core/src/api_vcx/api_handle/issuer_credential.rs
  libvcx_core/src/api_vcx/api_handle/schema.rs
  libvcx_core/src/lib.rs
  libvdrtools/indy-wallet/Cargo.toml
  libvdrtools/src/lib.rs
  libvdrtools/src/utils/mod.rs
Labels: hotfix

#888 ci: run libvcx tests with modular features
  .github/workflows/main.yml
  aries_vcx/src/common/primitives/revocation_registry.rs
  aries_vcx/src/core/profile/modular_libs_profile.rs
  aries_vcx/src/utils/mockdata/profile/mock_wallet.rs
  aries_vcx_core/src/errors/mapping_indyvdr.rs
  aries_vcx_core/src/ledger/indy_vdr_ledger.rs
  aries_vcx_core/src/wallet/agency_client_wallet.rs
  aries_vcx_core/src/wallet/base_wallet.rs
  aries_vcx_core/src/wallet/indy_wallet.rs
  libvcx/Cargo.toml
  libvcx/src/api_c/vcx.rs
  libvcx_core/Cargo.toml
  libvcx_core/src/api_vcx/api_global/pool.rs
  libvcx_core/src/api_vcx/api_global/profile.rs
  libvcx_core/src/api_vcx/api_global/state.rs
  libvcx_core/src/api_vcx/api_global/wallet.rs
  libvcx_core/src/api_vcx/api_handle/schema.rs
  libvcx_core/src/api_vcx/utils/devsetup.rs
Labels: skip-ios, skip-android

#901 Rename tails variables in prover code
  agents/node/vcxagent-core/src/utils/proofs.js
  aries_vcx/src/common/proofs/prover/prover_internal.rs
  aries_vcx/src/handlers/proof_presentation/types.rs
  aries_vcx/tests/utils/scenarios.rs
Labels: breaking
