Repository hyperledger/aries-vcx, pull requests merged in 2023-05, with the labels that each got.

#832 Remove extra warn log
  aries_vcx/src/protocols/proof_presentation/verifier/state_machine.rs
Labels: skip-ios, skip-android, skip-napi-m1, skip-ci

#828 Basic implementation of did:web resolver
  .github/workflows/main.yml
  Cargo.lock
  Cargo.toml
  did_resolver_web/Cargo.toml
  did_resolver_web/src/error/mod.rs
  did_resolver_web/src/error/parsing.rs
  did_resolver_web/src/lib.rs
  did_resolver_web/src/resolution/mod.rs
  did_resolver_web/src/resolution/resolver.rs
  did_resolver_web/tests/resolution.rs
Labels: skip-ci

#861 Split BaseLedger trait
  agents/rust/aries-vcx-agent/src/services/schema.rs
  aries_vcx/src/common/anoncreds.rs
  aries_vcx/src/common/keys.rs
  aries_vcx/src/common/ledger/transactions.rs
  aries_vcx/src/common/primitives/credential_definition.rs
  aries_vcx/src/common/primitives/credential_schema.rs
  aries_vcx/src/common/primitives/mod.rs
  aries_vcx/src/common/primitives/revocation_registry.rs
  aries_vcx/src/common/primitives/revocation_registry_delta.rs
  aries_vcx/src/common/proofs/prover/prover_internal.rs
  aries_vcx/src/common/proofs/verifier/verifier_internal.rs
  aries_vcx/src/common/test_utils.rs
  aries_vcx/src/core/profile/modular_libs_profile.rs
  aries_vcx/src/core/profile/profile.rs
  aries_vcx/src/core/profile/vdr_proxy_profile.rs
  aries_vcx/src/core/profile/vdrtools_profile.rs
  aries_vcx/src/global/author_agreement.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/mod.rs
  aries_vcx/src/utils/mockdata/mock_settings.rs
  aries_vcx/src/utils/mockdata/profile/mock_ledger.rs
  aries_vcx/src/utils/mockdata/profile/mock_profile.rs
  aries_vcx/tests/test_agency.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/test_creds_proofs_revocations.rs
  aries_vcx/tests/test_pool.rs
  aries_vcx/tests/utils/devsetup_agent.rs
  aries_vcx/tests/utils/scenarios.rs
  aries_vcx_core/src/global/mockdata/mock_settings.rs
  aries_vcx_core/src/indy/credentials/issuer/mod.rs
  aries_vcx_core/src/indy/primitives/revocation_registry.rs
  aries_vcx_core/src/ledger/base_ledger.rs
  aries_vcx_core/src/ledger/indy_ledger.rs
  aries_vcx_core/src/ledger/indy_vdr_ledger.rs
  aries_vcx_core/src/utils/mod.rs
  did_resolver_sov/src/reader/mod.rs
  did_resolver_sov/tests/resolution.rs
  libvcx_core/src/api_vcx/api_global/ledger.rs
  libvcx_core/src/api_vcx/api_global/pool.rs
  libvcx_core/src/api_vcx/api_global/profile.rs
  libvcx_core/src/api_vcx/api_handle/schema.rs
Labels: refactoring

#862 Split IndyVdrLedger and IndySdkLedger
  .github/workflows/main.yml
  aries_vcx/src/core/profile/modular_libs_profile.rs
  aries_vcx/src/core/profile/vdr_proxy_profile.rs
  aries_vcx/src/core/profile/vdrtools_profile.rs
  aries_vcx/src/utils/mockdata/profile/mock_ledger.rs
  aries_vcx_core/src/ledger/base_ledger.rs
  aries_vcx_core/src/ledger/indy_ledger.rs
  aries_vcx_core/src/ledger/indy_vdr_ledger.rs
  did_resolver_sov/src/reader/indy_reader.rs
  did_resolver_sov/src/reader/vdr_reader.rs
Labels: refactoring
