Repository hyperledger/aries-vcx, pull requests merged in 2023-09, with the labels that each got.

#965 Extract message sending from prover & verifier SMs
  .github/workflows/main.yml
  agents/rust/aries-vcx-agent/src/services/prover.rs
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  aries_vcx/src/handlers/proof_presentation/prover.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/src/protocols/proof_presentation/prover/state_machine.rs
  aries_vcx/src/protocols/proof_presentation/prover/states/presentation_proposal_sent.rs
  aries_vcx/src/protocols/proof_presentation/verifier/state_machine.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/utils/devsetup_alice.rs
  aries_vcx/tests/utils/devsetup_faber.rs
  aries_vcx/tests/utils/devsetup_util.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx_core/src/api_vcx/api_handle/disclosed_proof.rs
  libvcx_core/src/api_vcx/api_handle/proof.rs
  wrappers/vcx-napi-rs/index.js
Labels: refactoring

#946 Remove msg-sending IO for issuer and holder
  agents/node/vcxagent-core/demo/alice.js
  agents/node/vcxagent-core/demo/faber.js
  agents/node/vcxagent-core/demo/logger.js
  agents/node/vcxagent-core/src/services/service-cred-issuer.js
  agents/rust/aries-vcx-agent/src/services/holder.rs
  agents/rust/aries-vcx-agent/src/services/issuer.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/issuance/mediated_holder.rs
  aries_vcx/src/handlers/issuance/mediated_issuer.rs
  aries_vcx/src/handlers/mod.rs
  aries_vcx/src/handlers/revocation_notification/mod.rs
  aries_vcx/src/protocols/issuance/holder/state_machine.rs
  aries_vcx/src/protocols/issuance/holder/states/finished.rs
  aries_vcx/src/protocols/issuance/holder/states/mod.rs
  aries_vcx/src/protocols/issuance/holder/states/offer_received.rs
  aries_vcx/src/protocols/issuance/holder/states/proposal_set.rs
  aries_vcx/src/protocols/issuance/holder/states/request_set.rs
  aries_vcx/src/protocols/issuance/issuer/state_machine.rs
  aries_vcx/src/protocols/issuance/issuer/states/credential_set.rs
  aries_vcx/src/protocols/issuance/issuer/states/initial.rs
  aries_vcx/src/protocols/issuance/issuer/states/mod.rs
  aries_vcx/src/protocols/issuance/issuer/states/offer_sent.rs
  aries_vcx/src/protocols/issuance/issuer/states/offer_set.rs
  aries_vcx/src/protocols/issuance/issuer/states/proposal_received.rs
  aries_vcx/src/protocols/issuance/issuer/states/requested_received.rs
  aries_vcx/src/utils/mockdata/mockdata_credex.rs
  aries_vcx/src/utils/mockdata/profile/mock_anoncreds.rs
  aries_vcx/tests/test_creds_proofs.rs
  aries_vcx/tests/utils/devsetup_alice.rs
  aries_vcx/tests/utils/devsetup_faber.rs
  aries_vcx/tests/utils/devsetup_util.rs
  aries_vcx/tests/utils/scenarios.rs
  libvcx_core/src/api_vcx/api_handle/credential.rs
  libvcx_core/src/api_vcx/api_handle/issuer_credential.rs
  wrappers/node/src/api/common.ts
  wrappers/node/src/api/issuer-credential.ts
  wrappers/node/test/suite1/ariesvcx-issuer-credential.test.ts
  wrappers/vcx-napi-rs/index.d.ts
  wrappers/vcx-napi-rs/index.js
  wrappers/vcx-napi-rs/src/api/issuer_credential.rs
Labels: breaking

#969 Fix genesis file URL in vdrproxy config
  .github/workflows/main.yml
Labels: hotfix

#983 Integration test refactoring
  agents/rust/aries-vcx-agent/src/services/verifier.rs
  aries_vcx/src/common/anoncreds.rs
  aries_vcx/src/common/credentials/mod.rs
  aries_vcx/src/common/mod.rs
  aries_vcx/src/common/primitives/credential_definition.rs
  aries_vcx/src/common/primitives/credential_schema.rs
  aries_vcx/src/common/primitives/mod.rs
  aries_vcx/src/common/primitives/revocation_registry.rs
  aries_vcx/src/common/primitives/revocation_registry_delta.rs
  aries_vcx/src/common/proofs/verifier/verifier.rs
  aries_vcx/src/common/test_utils.rs
  aries_vcx/src/handlers/issuance/holder.rs
  aries_vcx/src/handlers/issuance/issuer.rs
  aries_vcx/src/handlers/proof_presentation/verifier.rs
  aries_vcx/tests/test_credential_issuance.rs
  aries_vcx/tests/test_credential_retrieval.rs
  aries_vcx/tests/test_pool.rs
  aries_vcx/tests/test_proof_presentation.rs
  aries_vcx/tests/test_revocations.rs
  aries_vcx/tests/utils/scenarios/credential_issuance.rs
  aries_vcx/tests/utils/scenarios/data.rs
  aries_vcx/tests/utils/scenarios/proof_presentation.rs
  aries_vcx_core/src/utils/constants.rs
  libvcx_core/src/api_vcx/api_handle/credential_def.rs
  libvcx_core/src/api_vcx/api_handle/proof.rs
  libvcx_core/src/api_vcx/api_handle/schema.rs
Labels: refactoring
