Repository hyperledger/aries-vcx, pull requests merged in 2024-01, with the labels that each got.

#1103 Fix clippy
  aries/misc/legacy/agency_client/src/internal/messaging.rs
Labels: ci

#1107 CI: Fix toolchain version
  .github/workflows/main.yml
  .github/workflows/mediator.pr.yml
Labels: review:level-1

#1084 feat: add new Wallet trait, implement for indy wallet
  Cargo.lock
  aries/aries_vcx/src/errors/error.rs
  aries/aries_vcx/src/errors/mapping_others.rs
  aries/aries_vcx_core/Cargo.toml
  aries/aries_vcx_core/src/errors/error.rs
  aries/aries_vcx_core/src/lib.rs
  aries/aries_vcx_core/src/wallet2/entry_tag.rs
  aries/aries_vcx_core/src/wallet2/indy_wallet/indy_did_wallet.rs
  aries/aries_vcx_core/src/wallet2/indy_wallet/indy_record_wallet.rs
  aries/aries_vcx_core/src/wallet2/indy_wallet/mod.rs
  aries/aries_vcx_core/src/wallet2/mod.rs
  aries/aries_vcx_core/src/wallet2/utils.rs
  aries/misc/legacy/libvcx_core/src/errors/error.rs
  aries/misc/legacy/libvcx_core/src/errors/mapping_from_ariesvcx.rs
  aries/misc/legacy/libvcx_core/src/errors/mapping_from_ariesvcxcore.rs
Labels: review:level-2
